name: Build Binaries

on:
  # Runs on pushes targeting the default branch
  push:

jobs:
  # Build job
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  publishRustLib:
    runs-on: ubuntu-latest
    name: Publish Rust Library
    needs: [ build ] # for ignoring bad builds
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Add SarGit Repo
        run: |
          cat <<EOF > ~/.cargo/config.toml
          [registry]
          default = "sargit"
          
          [registries.sargit]
          index = "sparse+https://git.sarsoo.xyz/api/packages/${{ secrets.DOCKERHUB_USERNAME }}/cargo/"
          
          [net]
          git-fetch-with-cli = true
          EOF

      - name: Add SarGit Credentials
        run: |
          cat <<EOF > ~/.cargo/credentials.toml
          [registries.sargit]
          token = "Bearer ${{ secrets.DOCKERHUB_TOKEN }}"
          EOF

      - name: Cargo Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --package finlib

  publishNPM:
    name: Publish NPM
    runs-on: ubuntu-latest
    needs: [ build ] # for ignoring bad builds
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Rust for WASM
        working-directory: ./finlib-wasm
        run: wasm-pack build --release

      - name: Change Package Name
        working-directory: ./finlib-wasm
        run: ./rename-pkg.sh

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 22
          registry-url: 'https://gitea.sheep-ghoul.ts.net/api/packages/sarsoo/npm/'

      - name: Publish
        working-directory: ./finlib-wasm/pkg
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}