name: Build Binaries

on:
  # Runs on pushes targeting the default branch
  push:

jobs:
  # Build job
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  buildPy:
    name: Build Python
    runs-on: ubuntu-latest
    needs: [ build ] # for ignoring bad builds
    steps:
      - uses: actions/checkout@v4 # get source
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install Maturin
        run: sudo apt update && sudo apt install -y python3-maturin

      - name: Build Python
        working-directory: ./pyfinlib
        run: maturin build

  buildWASM:
    name: Build WASM
    runs-on: ubuntu-latest
    needs: [ build ] # for ignoring bad builds
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Rust for WASM
        working-directory: ./finlib-wasm
        run: wasm-pack build

  publishNPM:
    name: Publish NPM
    runs-on: ubuntu-latest
    needs: [ buildWASM ] # for ignoring bad builds
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Rust for WASM
        working-directory: ./finlib-wasm
        run: wasm-pack build --release

      - name: Change Package Name
        working-directory: ./finlib-wasm
        run: ./rename-pkg.sh

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 22
          registry-url: 'https://gitea.sheep-ghoul.ts.net/api/packages/sarsoo/npm/'

      - name: Publish
        working-directory: ./finlib-wasm/pkg
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publishRustLib:
    runs-on: ubuntu-latest
    name: Publish Rust Library
    needs: [ build ] # for ignoring bad builds
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Add SarGit Repo
        run: |
          cat <<EOF > ~/.cargo/config.toml
          [registry]
          default = "sargit"

          [registries.sargit]
          index = "sparse+https://git.sarsoo.xyz/api/packages/${{ secrets.DOCKERHUB_USERNAME }}/cargo/"

          [net]
          git-fetch-with-cli = true
          EOF

      - name: Add SarGit Credentials
        run: |
          cat <<EOF > ~/.cargo/credentials.toml
          [registries.sargit]
          token = "Bearer ${{ secrets.DOCKERHUB_TOKEN }}"
          EOF

      - name: Cargo Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --package finlib --registry sargit

  publishPy:
    runs-on: ubuntu-latest
    name: Publish Python Library
    needs: [ build ] # for ignoring bad builds
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - uses: PyO3/maturin-action@v1
        with:
          command: publish
          args: -r https://gitea.sheep-ghoul.ts.net/api/packages/sarsoo/pypi/simple -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          working-directory: ./pyfinlib