// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace FinLib
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "libfinlib_ffi";



        [DllImport(__DllName, EntryPoint = "interest_compound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double interest_compound(double principal, double rate, double time, double n);

        [DllImport(__DllName, EntryPoint = "covariance", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NullableFloat covariance(double* arr, nuint len, double* arr_two, nuint len_two);

        [DllImport(__DllName, EntryPoint = "historical_value_at_risk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NullableFloat historical_value_at_risk(double* arr, nuint len, double confidence);

        [DllImport(__DllName, EntryPoint = "varcovar_value_at_risk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NullableFloat varcovar_value_at_risk(double* arr, nuint len, double confidence);

        [DllImport(__DllName, EntryPoint = "scale_value_at_risk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double scale_value_at_risk(double initial_value, nint time_cycles);

        [DllImport(__DllName, EntryPoint = "portfolio_asset_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PortfolioAsset_native* portfolio_asset_new(byte* name, int name_len, double quantity, double* values, nuint len);

        [DllImport(__DllName, EntryPoint = "portfolio_asset_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void portfolio_asset_destroy(PortfolioAsset_native* asset);

        [DllImport(__DllName, EntryPoint = "portfolio_asset_apply_rates_of_change", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void portfolio_asset_apply_rates_of_change(PortfolioAsset_native* asset);

        [DllImport(__DllName, EntryPoint = "portfolio_asset_get_mean_and_std", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Tuple portfolio_asset_get_mean_and_std(PortfolioAsset_native* asset);

        [DllImport(__DllName, EntryPoint = "portfolio_asset_current_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double portfolio_asset_current_value(PortfolioAsset_native* asset);

        [DllImport(__DllName, EntryPoint = "portfolio_asset_current_total_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double portfolio_asset_current_total_value(PortfolioAsset_native* asset);

        [DllImport(__DllName, EntryPoint = "portfolio_asset_profit_loss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NullableFloat portfolio_asset_profit_loss(PortfolioAsset_native* asset);

        [DllImport(__DllName, EntryPoint = "portfolio_asset_payoff", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double portfolio_asset_payoff(PortfolioAsset_native* asset, NullableFloat underlying);

        [DllImport(__DllName, EntryPoint = "portfolio_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Portfolio_native* portfolio_new();

        [DllImport(__DllName, EntryPoint = "portfolio_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void portfolio_destroy(Portfolio_native* portfolio);

        [DllImport(__DllName, EntryPoint = "portfolio_add_asset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void portfolio_add_asset(Portfolio_native* portfolio, PortfolioAsset_native* asset);

        [DllImport(__DllName, EntryPoint = "portfolio_apply_rates_of_change", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void portfolio_apply_rates_of_change(Portfolio_native* portfolio);

        [DllImport(__DllName, EntryPoint = "portfolio_valid_sizes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool portfolio_valid_sizes(Portfolio_native* portfolio);

        [DllImport(__DllName, EntryPoint = "portfolio_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint portfolio_size(Portfolio_native* portfolio);

        [DllImport(__DllName, EntryPoint = "portfolio_profit_loss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NullableFloat portfolio_profit_loss(Portfolio_native* asset);

        [DllImport(__DllName, EntryPoint = "portfolio_payoff", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double portfolio_payoff(Portfolio_native* asset, NullableFloat underlying);

        [DllImport(__DllName, EntryPoint = "portfolio_is_valid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool portfolio_is_valid(Portfolio_native* portfolio);

        [DllImport(__DllName, EntryPoint = "portfolio_get_mean_and_std", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Tuple portfolio_get_mean_and_std(Portfolio_native* portfolio);

        [DllImport(__DllName, EntryPoint = "portfolio_value_at_risk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NullableFloat portfolio_value_at_risk(Portfolio_native* portfolio, double confidence, double initial_investment);

        [DllImport(__DllName, EntryPoint = "portfolio_value_at_risk_percent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NullableFloat portfolio_value_at_risk_percent(Portfolio_native* portfolio, double confidence);

        [DllImport(__DllName, EntryPoint = "relative_strength_indicator", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double relative_strength_indicator(double time_period, double average_gain, double average_loss);

        [DllImport(__DllName, EntryPoint = "relative_strength_indicator_smoothed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double relative_strength_indicator_smoothed(double time_period, double previous_average_gain, double current_gain, double previous_average_loss, double current_loss);

        [DllImport(__DllName, EntryPoint = "price_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Price_native* price_new(double price, Side_native side);

        [DllImport(__DllName, EntryPoint = "price_set_val", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void price_set_val(Price_native* price, double new_price);

        [DllImport(__DllName, EntryPoint = "price_set_side", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void price_set_side(Price_native* price, Side_native new_side);

        [DllImport(__DllName, EntryPoint = "price_get_val", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double price_get_val(Price_native* price);

        [DllImport(__DllName, EntryPoint = "price_get_side", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Side_native price_get_side(Price_native* price);

        [DllImport(__DllName, EntryPoint = "price_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void price_destroy(Price_native* asset);

        [DllImport(__DllName, EntryPoint = "price_pair_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PricePair_native* price_pair_new(double bid, double offer);

        [DllImport(__DllName, EntryPoint = "price_pair_set_bid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void price_pair_set_bid(PricePair_native* price, double new_price);

        [DllImport(__DllName, EntryPoint = "price_pair_set_offer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void price_pair_set_offer(PricePair_native* price, double new_price);

        [DllImport(__DllName, EntryPoint = "price_pair_get_bid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double price_pair_get_bid(PricePair_native* price);

        [DllImport(__DllName, EntryPoint = "price_pair_get_offer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double price_pair_get_offer(PricePair_native* price);

        [DllImport(__DllName, EntryPoint = "price_pair_spread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double price_pair_spread(PricePair_native* price);

        [DllImport(__DllName, EntryPoint = "price_pair_midpoint", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double price_pair_midpoint(PricePair_native* price);

        [DllImport(__DllName, EntryPoint = "price_pair_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void price_pair_destroy(PricePair_native* asset);

        [DllImport(__DllName, EntryPoint = "curve_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Curve_native* curve_new(CurveType_native curve_type);

        [DllImport(__DllName, EntryPoint = "curve_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint curve_size(Curve_native* curve);

        [DllImport(__DllName, EntryPoint = "curve_add_rate_from", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void curve_add_rate_from(Curve_native* curve, double bid, double offer, int year, uint month, uint day);

        [DllImport(__DllName, EntryPoint = "curve_get_rate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PricePair_native* curve_get_rate(Curve_native* curve, int year, uint month, uint day);

        [DllImport(__DllName, EntryPoint = "curve_get_absolute_rate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PricePair_native* curve_get_absolute_rate(Curve_native* curve, int year, uint month, uint day);

        [DllImport(__DllName, EntryPoint = "curve_get_cumulative_rate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PricePair_native* curve_get_cumulative_rate(Curve_native* curve, int year, uint month, uint day);

        [DllImport(__DllName, EntryPoint = "curve_get_carry_rate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PricePair_native* curve_get_carry_rate(Curve_native* curve, int from_year, uint from_month, uint from_day, int to_year, uint to_month, uint to_day);

        [DllImport(__DllName, EntryPoint = "curve_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void curve_destroy(Curve_native* curve);

        [DllImport(__DllName, EntryPoint = "swap_from", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Swap_native* swap_from(double fixed_rate, Side_native fixed_side, double premium);

        [DllImport(__DllName, EntryPoint = "swap_payoff", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double swap_payoff(Swap_native* swap, double floating_rate);

        [DllImport(__DllName, EntryPoint = "swap_payoff_from_multiple", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double swap_payoff_from_multiple(Swap_native* swap, double* values, nuint len);

        [DllImport(__DllName, EntryPoint = "swap_profit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double swap_profit(Swap_native* swap, double floating_rate);

        [DllImport(__DllName, EntryPoint = "swap_profit_from_multiple", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double swap_profit_from_multiple(Swap_native* swap, double* values, nuint len);

        [DllImport(__DllName, EntryPoint = "swap_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void swap_destroy(Swap_native* swap);

        [DllImport(__DllName, EntryPoint = "option_vars_from", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern OptionVariables_native* option_vars_from(double underlying_price, double strike_price, double volatility, double risk_free_interest_rate, double dividend, double time_to_expiration);

        [DllImport(__DllName, EntryPoint = "option_vars_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void option_vars_destroy(OptionVariables_native* option);

        [DllImport(__DllName, EntryPoint = "option_surface_parameters_from", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern OptionSurfaceParameters_native* option_surface_parameters_from(nint underlying_price_range_min, nint underlying_price_range_max, double underlying_price_min, double underlying_price_max, nint strike_price_range_min, nint strike_price_range_max, double strike_price_min, double strike_price_max, nint volatility_range_min, nint volatility_range_max, double volatility_min, double volatility_max, nint risk_free_interest_rate_range_min, nint risk_free_interest_rate_range_max, double risk_free_interest_rate_min, double risk_free_interest_rate_max, nint dividend_range_min, nint dividend_range_max, double dividend_min, double dividend_max, nint time_to_expiration_range_min, nint time_to_expiration_range_max, double time_to_expiration_min, double time_to_expiration_max);

        [DllImport(__DllName, EntryPoint = "option_surface_parameters_walk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern OptionsSurface_native* option_surface_parameters_walk(OptionSurfaceParameters_native* option);

        [DllImport(__DllName, EntryPoint = "option_surface_parameters_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void option_surface_parameters_destroy(OptionSurfaceParameters_native* option);

        [DllImport(__DllName, EntryPoint = "option_surface_generate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void option_surface_generate(OptionsSurface_native* option);

        [DllImport(__DllName, EntryPoint = "option_surface_par_generate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void option_surface_par_generate(OptionsSurface_native* option);

        [DllImport(__DllName, EntryPoint = "option_surface_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void option_surface_destroy(OptionsSurface_native* option);

        [DllImport(__DllName, EntryPoint = "option_strategy_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern OptionStrategy_native* option_strategy_new();

        [DllImport(__DllName, EntryPoint = "option_strategy_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint option_strategy_size(OptionStrategy_native* option);

        [DllImport(__DllName, EntryPoint = "option_strategy_add_component", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void option_strategy_add_component(OptionStrategy_native* option, OptionStrategyComponent_native* component);

        [DllImport(__DllName, EntryPoint = "option_strategy_payoff", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double option_strategy_payoff(OptionStrategy_native* option, double underlying);

        [DllImport(__DllName, EntryPoint = "option_strategy_profit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double option_strategy_profit(OptionStrategy_native* option, double underlying);

        [DllImport(__DllName, EntryPoint = "option_strategy_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void option_strategy_destroy(OptionStrategy_native* option);

        [DllImport(__DllName, EntryPoint = "option_strategy_component_from", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern OptionStrategyComponent_native* option_strategy_component_from(OptionType_native option_type, Side_native side, double strike, double premium);

        [DllImport(__DllName, EntryPoint = "option_strategy_component_payoff", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double option_strategy_component_payoff(OptionStrategyComponent_native* option, double underlying);

        [DllImport(__DllName, EntryPoint = "option_strategy_component_profit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double option_strategy_component_profit(OptionStrategyComponent_native* option, double underlying);

        [DllImport(__DllName, EntryPoint = "option_strategy_component_will_be_exercised", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool option_strategy_component_will_be_exercised(OptionStrategyComponent_native* option, double underlying);

        [DllImport(__DllName, EntryPoint = "option_strategy_component_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void option_strategy_component_destroy(OptionStrategyComponent_native* option);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Tuple
    {
        public double one;
        public double two;
        [MarshalAs(UnmanagedType.U1)] public bool is_valid;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct NullableFloat
    {
        public double val;
        [MarshalAs(UnmanagedType.U1)] public bool is_valid;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Portfolio_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PortfolioAsset_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Price_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PricePair_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Curve_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Swap_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct OptionVariables_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct OptionSurfaceParameters_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct OptionsSurface_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct OptionStrategyComponent_native
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct OptionStrategy_native
    {
    }


    internal enum Side_native : byte
    {
        Buy,
        Sell,
    }

    internal enum CurveType_native : byte
    {
        Absolute,
        Differential,
    }

    internal enum OptionType_native : byte
    {
        Call,
        Put,
    }


}
