[package]
name = "finlib-ffi"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
finlib = { path = "../finlib" }

[build-dependencies]
cbindgen = "0.28.0"
csbindgen = "1.8.0"