#pragma once

/* Generated with cbindgen:0.28.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


namespace finlib {


extern "C" {

uint64_t add(uint64_t left, uint64_t right);

float interest_compound(float principal, float rate, float time, float n);

}  // extern "C"

}  // namespace finlib
